<a href="https://colab.research.google.com/github/igoradriano/Inteligencia-Artificial/blob/main/Vetor_ordenado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vetor ordenado

In [423]:
import numpy as np
import random

In [424]:
class VetorOrdenado:
  
  def __init__(self, capacidade):
    self.capacidade = capacidade  #parâmetro da classe construtora é passado como valor do atributo da classe
    self.ultima_posicao = -1    #vetor vazio logo no inicio recebe ultima aposição = -1
    self.valores = np.empty(self.capacidade, dtype=int) #A função empty () é usada para criar um novo array numpy vazio com a capacidade que passaremos, e tipo de dados inteiro.
    
  # O(n) --> MÉTODO PARA IMPRIMIR OS DADOS

  def imprime(self):
    if self.ultima_posicao == -1:  
      print('O vetor está vazio')
    else:
      for i in range(self.ultima_posicao + 1):  #para o primeiro caso será será -1(array vazio) + 1(primeiro termo) = 0 (tamanho do array)
        print(i, ' - ', self.valores[i])  #dessa forma, só iremos imprimir os próximos termos do array através do range(ultima_posicao)

  # O(n)  --> MÉTODO PARA INSERIR DADOS

  def insere(self, valor):
    if self.ultima_posicao == self.capacidade - 1: 
      print('Capacidade máxima atingida')
      return

  # --------> PESQUISA POR VALOR NO ARRAY E RETORNA A POSIÇÃO QUE DEVE SER INSERIDO O NOVO VALOR

    posicao = 0
    for i in range(self.ultima_posicao + 1):   #para o primeiro caso será será -1(array vazio) + 1(primeiro termo) = 0 (tamanho do array)
      posicao = i
      if self.valores[i] > valor:   #se o valor anterior desta posição for maior que o novo valor a ser inserido:
        break
      if i == self.ultima_posicao:  #cqso o valor a ser inserido seja maior que todos os valores do array, atualizar a posição com + 1
        posicao = i + 1

  #---------> AFASTA VALORES CASO NECESSÁRIO E DEPOIS INSERE O VALOR DESEJADO
    x = self.ultima_posicao
    while x >= posicao:
      self.valores[x + 1] = self.valores[x]  #jogando os valores do vetor para o final do vetor, abrindo espaço para inserir novo valor
      x -= 1

    self.valores[posicao] = valor  #insere o valor na posição que descobrimos com a PESQUISA
    self.ultima_posicao += 1  #Atualiza o valor da ultima posição 
#-----------------------------------------------------------------------------------------------------------------------------------
  # O(n) PESQUISA LINEAR
  def pesquisa_linear(self, valor):
    for i in range(self.ultima_posicao + 1):
      if self.valores[i] > valor:   # se o valor do vetor naquela posicao for maior que o valor que estou procurando
        print("Já passamos por um valor maior que o procurado, significa que ele não está presente no vetor")
        return -1
      if self.valores[i] == valor:   # se o valor do vetor naquela posicao for igual ao valor que estou procurando retorne a posicao deste valor no vetor
        print(f"A posição do seu valor é :{i}")
        return i
      if i == self.ultima_posicao:    # se a posição onde parou a pesquisa for igual a ultima posicao 
        print("Chegamos ao final do vetor e nada foi encontrado")
        return -1
        
#--------------------------------------------------------------------------------------------------------------------------------------
  # O(log n) PESQUISA BINÁRIA
  def pesquisa_binaria(self, valor):
    limite_inferior = 0
    limite_superior = self.ultima_posicao
    i = 0 #DEBUG
    while True:
      posicao_atual = int((limite_inferior + limite_superior) / 2)   # Define o centro do vetor
      print(f"Testamos sua posição central {posicao_atual}")
      # Se achou na primeira tentativa
      if self.valores[posicao_atual] == valor:
        print(f"Encontramos o seu valor, foram feitas {i} interacoes ") #DEBUG
        return posicao_atual
      # Se não achou
      elif limite_inferior > limite_superior:
        print(f"Seu valor não está no vetor, foram feitas {i} interacoes") #DEBUG
        return -1
      # Divide os limites
      else:
        i += 1 #DEBUG
        # Limite inferior
        if self.valores[posicao_atual] < valor:
          limite_inferior = posicao_atual + 1
          print(f"O valor está acima de {self.valores[posicao_atual]}, posicao : {posicao_atual}, mudamos sua posicao inferior para {posicao_atual + 1} / posicao superior pemanece {limite_superior} ") #DEBUG
        # Limite superior
        else:
          limite_superior = posicao_atual - 1
          print(f"O valor está abaixo de {self.valores[posicao_atual]}, posicao: {posicao_atual}, mudamos sua posicao superior para {posicao_atual - 1} / posicao inferior permance {limite_inferior}") #DEBUG

  # O(n)
  def excluir(self, valor):
    posicao = self.pesquisa_linear(valor)
    if posicao == -1:
      return -1
    else:
      for i in range(posicao, self.ultima_posicao):
        self.valores[i] = self.valores[i + 1]
      
      self.ultima_posicao -= 1

In [425]:
vetor = VetorOrdenado(10)
vetor.imprime()

O vetor está vazio


In [426]:
vetor.insere(6)
vetor.imprime()

0  -  6


In [427]:
vetor.insere(4)
vetor.imprime()

0  -  4
1  -  6


In [428]:
vetor.insere(3)
vetor.imprime()

0  -  3
1  -  4
2  -  6


In [429]:
vetor.insere(5)
vetor.imprime()

0  -  3
1  -  4
2  -  5
3  -  6


In [430]:
vetor.insere(1)
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  5
4  -  6


In [431]:
vetor.insere(8)
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  5
4  -  6
5  -  8


In [433]:
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  5
4  -  6
5  -  8


In [434]:
vetor.pesquisa_linear(8)

A posição do seu valor é :5


5

In [435]:
vetor.pesquisa_linear(2)

Já passamos por um valor maior que o procurado, significa que ele não está presente no vetor


-1

In [436]:
vetor.pesquisa_linear(9)

Chegamos ao final do vetor e nada foi encontrado


-1

In [437]:
vetor.excluir(5)
vetor.imprime()

A posição do seu valor é :3
0  -  1
1  -  3
2  -  4
3  -  6
4  -  8


In [438]:
vetor.excluir(1)
vetor.imprime()

A posição do seu valor é :0
0  -  3
1  -  4
2  -  6
3  -  8


In [439]:
vetor.excluir(8)
vetor.imprime()

A posição do seu valor é :3
0  -  3
1  -  4
2  -  6


In [440]:
vetor.excluir(9)

Chegamos ao final do vetor e nada foi encontrado


-1

In [441]:
vetor = VetorOrdenado(10)
vetor.insere(8)
vetor.insere(9)
vetor.insere(4)
vetor.insere(1)
vetor.insere(5)
vetor.insere(7)
vetor.insere(11)
vetor.insere(13)
vetor.insere(2)
vetor.imprime()

0  -  1
1  -  2
2  -  4
3  -  5
4  -  7
5  -  8
6  -  9
7  -  11
8  -  13


In [442]:
vetor.pesquisa_binaria(7)

Testamos sua posição central 4
Encontramos o seu valor, foram feitas 0 interacoes 


4

In [452]:
vetor.pesquisa_binaria(5)

Testamos sua posição central 4
O valor está abaixo de 7, posicao: 4, mudamos sua posicao superior para 3 / posicao inferior permance 0
Testamos sua posição central 1
O valor está acima de 2, posicao : 1, mudamos sua posicao inferior para 2 / posicao superior pemanece 3 
Testamos sua posição central 2
O valor está acima de 4, posicao : 2, mudamos sua posicao inferior para 3 / posicao superior pemanece 3 
Testamos sua posição central 3
Encontramos o seu valor, foram feitas 3 interacoes 


3

In [444]:
vetor.pesquisa_binaria(13)

Testamos sua posição central 4
O valor está acima de 7, posicao : 4, mudamos sua posicao inferior para 5 / posicao superior pemanece 8 
Testamos sua posição central 6
O valor está acima de 9, posicao : 6, mudamos sua posicao inferior para 7 / posicao superior pemanece 8 
Testamos sua posição central 7
O valor está acima de 11, posicao : 7, mudamos sua posicao inferior para 8 / posicao superior pemanece 8 
Testamos sua posição central 8
Encontramos o seu valor, foram feitas 3 interacoes 


8

In [445]:
vetor.pesquisa_binaria(20)

Testamos sua posição central 4
O valor está acima de 7, posicao : 4, mudamos sua posicao inferior para 5 / posicao superior pemanece 8 
Testamos sua posição central 6
O valor está acima de 9, posicao : 6, mudamos sua posicao inferior para 7 / posicao superior pemanece 8 
Testamos sua posição central 7
O valor está acima de 11, posicao : 7, mudamos sua posicao inferior para 8 / posicao superior pemanece 8 
Testamos sua posição central 8
O valor está acima de 13, posicao : 8, mudamos sua posicao inferior para 9 / posicao superior pemanece 8 
Testamos sua posição central 8
Seu valor não está no vetor, foram feitas 4 interacoes


-1

In [459]:
vetor2 = VetorOrdenado(200)
for i in range(200):
  vetor2.insere(random.randint(0,10000))
  vetor2.imprime()

A saída de streaming foi truncada nas últimas 5000 linhas.
49  -  2855
50  -  2859
51  -  2861
52  -  2894
53  -  3004
54  -  3019
55  -  3142
56  -  3183
57  -  3335
58  -  3369
59  -  3388
60  -  3416
61  -  3424
62  -  3447
63  -  3568
64  -  3666
65  -  3839
66  -  3869
67  -  3886
68  -  4006
69  -  4045
70  -  4069
71  -  4075
72  -  4358
73  -  4360
74  -  4361
75  -  4372
76  -  4433
77  -  4443
78  -  4464
79  -  4470
80  -  4490
81  -  4518
82  -  4562
83  -  4966
84  -  4982
85  -  5052
86  -  5123
87  -  5128
88  -  5158
89  -  5208
90  -  5220
91  -  5256
92  -  5302
93  -  5353
94  -  5689
95  -  5715
96  -  5783
97  -  5908
98  -  5965
99  -  5991
100  -  6102
101  -  6153
102  -  6170
103  -  6210
104  -  6231
105  -  6237
106  -  6244
107  -  6288
108  -  6515
109  -  6539
110  -  6572
111  -  6608
112  -  6625
113  -  6696
114  -  6934
115  -  6983
116  -  7024
117  -  7107
118  -  7151
119  -  7193
120  -  7211
121  -  7227
122  -  7233
123  -  7273
124  -  7293
125 

In [460]:
vetor2.pesquisa_binaria(145)

Testamos sua posição central 99
O valor está abaixo de 4966, posicao: 99, mudamos sua posicao superior para 98 / posicao inferior permance 0
Testamos sua posição central 49
O valor está abaixo de 2584, posicao: 49, mudamos sua posicao superior para 48 / posicao inferior permance 0
Testamos sua posição central 24
O valor está abaixo de 1796, posicao: 24, mudamos sua posicao superior para 23 / posicao inferior permance 0
Testamos sua posição central 11
O valor está abaixo de 688, posicao: 11, mudamos sua posicao superior para 10 / posicao inferior permance 0
Testamos sua posição central 5
O valor está abaixo de 365, posicao: 5, mudamos sua posicao superior para 4 / posicao inferior permance 0
Testamos sua posição central 2
O valor está abaixo de 218, posicao: 2, mudamos sua posicao superior para 1 / posicao inferior permance 0
Testamos sua posição central 0
O valor está acima de 12, posicao : 0, mudamos sua posicao inferior para 1 / posicao superior pemanece 1 
Testamos sua posição centr

-1

In [461]:
vetor2.pesquisa_linear(145)

Já passamos por um valor maior que o procurado, significa que ele não está presente no vetor


-1

In [446]:
#>>> np.empty(2)
#array([  6.95033087e-310,   1.69970835e-316])
#>>> np.empty(32)
#array([  6.95033087e-310,   1.65350412e-316,   6.95032869e-310,
   #      6.95032869e-310,   6.95033051e-310,   6.95033014e-310,
   #      6.95033165e-310,   6.95033167e-310,   6.95033163e-310,
   #      6.95032955e-310,   6.95033162e-310,   6.95033166e-310,
   #      6.95033160e-310,   6.95033163e-310,   6.95033162e-310,
   #      6.95033167e-310,   6.95033167e-310,   6.95033167e-310,
   #      6.95033167e-310,   6.95033158e-310,   6.95033160e-310,
   #      6.95033164e-310,   6.95033162e-310,   6.95033051e-310,
   #     6.95033166e-310,   6.95033161e-310,   2.97403466e+289,
   #      7.55774284e+091,   1.31611495e+294])
#>>> np.empty([2, 2])
#array([[7.74860419e-304, 8.32155212e-317],
   #   [0.00000000e+000, 0.00000000e+000]])
#>>> np.empty([2, 3])
#array([[  6.95033087e-310,   1.68240973e-316,   6.95032825e-310],
   #     [  6.95032825e-310,   6.95032825e-310,   6.95032825e-310]])