<a href="https://colab.research.google.com/github/igoradriano/Inteligencia-Artificial/blob/main/Vetor_ordenado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vetor ordenado

In [1]:
import numpy as np

In [2]:
class VetorOrdenado:
  
  def __init__(self, capacidade):
    self.capacidade = capacidade  #parâmetro da classe construtora é passado como valor do atributo da classe
    self.ultima_posicao = -1    #vetor vazio logo no inicio recebe ultima aposição = -1
    self.valores = np.empty(self.capacidade, dtype=int) #A função empty () é usada para criar um novo array numpy vazio com a capacidade que passaremos, e tipo de dados inteiro.
    print(self.valores)
  # O(n) --> Método para mostrar os dados
  def imprime(self):
    if self.ultima_posicao == -1:
      print('O vetor está vazio')
    else:
      for i in range(self.ultima_posicao + 1):  #para o primeiro caso será será -1(array vazio) + 1(primeiro termo) = 0 (tamanho do array)
        print(i, ' - ', self.valores[i])  #dessa forma, só iremos imprimir os próximos termos do array através do rang(ultima_posicao)

  # O(n)
  def insere(self, valor):
    if self.ultima_posicao == self.capacidade - 1:
      print('Capacidade máxima atingida')
      return

    posicao = 0
    for i in range(self.ultima_posicao + 1):
      posicao = i
      if self.valores[i] > valor:
        break
      if i == self.ultima_posicao:
        posicao = i + 1

    x = self.ultima_posicao
    while x >= posicao:
      self.valores[x + 1] = self.valores[x]
      x -= 1

    self.valores[posicao] = valor
    self.ultima_posicao += 1

  # O(n)
  def pesquisa_linear(self, valor):
    for i in range(self.ultima_posicao + 1):
      if self.valores[i] > valor:
        return -1
      if self.valores[i] == valor:
        return i
      if i == self.ultima_posicao:
        return -1

  # O(log n)
  def pesquisa_binaria(self, valor):
    limite_inferior = 0
    limite_superior = self.ultima_posicao

    while True:
      posicao_atual = int((limite_inferior + limite_superior) / 2)
      # Se achou na primeira tentativa
      if self.valores[posicao_atual] == valor:
        return posicao_atual
      # Se não achou
      elif limite_inferior > limite_superior:
        return -1
      # Divide os limites
      else:
        # Limite inferior
        if self.valores[posicao_atual] < valor:
          limite_inferior = posicao_atual + 1
        # Limite superior
        else:
          limite_superior = posicao_atual - 1

  # O(n)
  def excluir(self, valor):
    posicao = self.pesquisar(valor)
    if posicao == -1:
      return -1
    else:
      for i in range(posicao, self.ultima_posicao):
        self.valores[i] = self.valores[i + 1]
      
      self.ultima_posicao -= 1

In [ ]:
vetor = VetorOrdenado(10)
vetor.imprime()

O vetor está vazio


In [ ]:
vetor.insere(6)
vetor.imprime()

0  -  6


In [ ]:
vetor.insere(4)
vetor.imprime()

0  -  4
1  -  6


In [ ]:
vetor.insere(3)
vetor.imprime()

0  -  3
1  -  4
2  -  6


In [ ]:
vetor.insere(5)
vetor.imprime()

0  -  3
1  -  4
2  -  5
3  -  6


In [ ]:
vetor.insere(1)
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  5
4  -  6


In [ ]:
vetor.insere(8)
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  5
4  -  6
5  -  8


In [ ]:
vetor.pesquisar(3)

1

In [ ]:
vetor.pesquisar(2)

-1

In [ ]:
vetor.pesquisar(9)

-1

In [ ]:
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  5
4  -  6
5  -  8


In [ ]:
vetor.excluir(5)
vetor.imprime()

0  -  1
1  -  3
2  -  4
3  -  6
4  -  8


In [ ]:
vetor.excluir(1)
vetor.imprime()

0  -  3
1  -  4
2  -  6
3  -  8


In [ ]:
vetor.excluir(8)
vetor.imprime()

0  -  3
1  -  4
2  -  6


In [ ]:
vetor.excluir(9)

-1

In [ ]:
vetor = VetorOrdenado(10)
vetor.insere(8)
vetor.insere(9)
vetor.insere(4)
vetor.insere(1)
vetor.insere(5)
vetor.insere(7)
vetor.insere(11)
vetor.insere(13)
vetor.insere(2)
vetor.imprime()

0  -  1
1  -  2
2  -  4
3  -  5
4  -  7
5  -  8
6  -  9
7  -  11
8  -  13


In [ ]:
vetor.pesquisa_binaria(7)

4

In [ ]:
vetor.pesquisa_binaria(5)

3

In [ ]:
vetor.pesquisa_binaria(13)

8

In [ ]:
vetor.pesquisa_binaria(20)

-1

In [ ]:
#>>> np.empty(2)
#array([  6.95033087e-310,   1.69970835e-316])
#>>> np.empty(32)
#array([  6.95033087e-310,   1.65350412e-316,   6.95032869e-310,
   #      6.95032869e-310,   6.95033051e-310,   6.95033014e-310,
   #      6.95033165e-310,   6.95033167e-310,   6.95033163e-310,
   #      6.95032955e-310,   6.95033162e-310,   6.95033166e-310,
   #      6.95033160e-310,   6.95033163e-310,   6.95033162e-310,
   #      6.95033167e-310,   6.95033167e-310,   6.95033167e-310,
   #      6.95033167e-310,   6.95033158e-310,   6.95033160e-310,
   #      6.95033164e-310,   6.95033162e-310,   6.95033051e-310,
   #     6.95033166e-310,   6.95033161e-310,   2.97403466e+289,
   #      7.55774284e+091,   1.31611495e+294])
#>>> np.empty([2, 2])
#array([[7.74860419e-304, 8.32155212e-317],
   #   [0.00000000e+000, 0.00000000e+000]])
#>>> np.empty([2, 3])
#array([[  6.95033087e-310,   1.68240973e-316,   6.95032825e-310],
   #     [  6.95032825e-310,   6.95032825e-310,   6.95032825e-310]])